Problems 9 with belarusian
bsu-docs/discrete-mathematics-problems pull request #10
Opened 2019-03-07 21:15 UTC by KlicOgogo

2019-03-08 14:20 UTC, UladBohdan requested changes

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Знайдзіце колькасць 7-літарных пароляў, якія складаюцца з сімвалаў алфавіта $\{a, b, \dots, z \}$, якія: (а)~складаюцца з непаўторных літар; (б)~складаюцца з непаўторных літар і літары $a$ і $b$ не
"непаўторны" гэта ўсё ж больш "неповторимый" чым "неповторяющийся". мб "адрозны" тут лепш?

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе чатырохзначных натуральных лікаў, лічбы якіх не паўтараюцца і прыналежаць мноству $\{0, 1, 2, 3, 4, 5\}$? Колькі з іх цотных лікаў?}
"колькі з іх" - мо "колькі сярод іх"?

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Нумар карткі складаецца з паслядоўнасці трох літар з  $\{a, b, \dots, z \}$, якая следуе за паслядоўнасцю з трох лічбаў з $\{0, 1, \dots, 9 \}$. Колькі ёсць нумароў, калі адначасовае ўжыванне лічбы
"якая следуе" - гучыць неяк кепска. мо "якая ідзе пасля" ці "якая ідзе за"?

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе $n$-значных натуральных лікаў, якія дзеляцца на 4 і ўтвораныя з дапамогай лічбаў 0, 1, 2, 3, 4, 5?}
"і ўтвораныя" - мо "і якія ўтвораныя"?

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Няхай зададзеныя няпустыя мноствы $X$ і $Y$, $|X|=m$, $|Y|=n$. Колькі існуе: (а)~усялякіх адлюстраванняў $f : X \rightarrow Y$; (б)~усялякіх ін'ектыўных адлюстраванняў $f : X \rightarrow Y$; (в)~уся
"няпустыя" - "нЕпустыя"?

у пункце (а) - можа проста пазбавіцца слова "усялякіх"? сэнс жа не мяняецца, а гучыць лепей. хаця можна і пакінуць.

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе ўпарадкаваных пар $(a,b)$ натуральных лікаў $a$ і $b$, для якіх $\text{НАК}(a,b) = 2^{3} \cdot 5^{7}\cdot 11^{13}$?}
выкарыстоўваць скарачэнні `gcd`/`lcm` было б значнай натуральней, магчыма

2019-03-08 14:20 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Вызначыце колькасць: (а)~бінарных матрыц памеру $m \times n$; (б)~бінарных матрыц памеру $m \times n$, у якіх радкі папарна адрозныя; (в)~бінарных матрыц памеру $m \times n$, у якіх у кожным радку і
"чотная" - "Цотная"

2019-03-08 20:14 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Колькі існуе ўпарадкаваных пар $(a,b)$ натуральных лікаў $a$ і $b$, для якіх $\text{НАК}(a,b) = 2^{3} \cdot 5^{7}\cdot 11^{13}$?}
Думаю, у беларускамоўнай матэматыцы абазначэнні прыняты, таму трэба іх ужываць

2019-03-08 20:15 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Няхай зададзеныя няпустыя мноствы $X$ і $Y$, $|X|=m$, $|Y|=n$. Колькі існуе: (а)~усялякіх адлюстраванняў $f : X \rightarrow Y$; (б)~усялякіх ін'ектыўных адлюстраванняў $f : X \rightarrow Y$; (в)~уся
Прыбяру

2019-03-08 20:16 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Колькі існуе $n$-значных натуральных лікаў, якія дзеляцца на 4 і ўтвораныя з дапамогай лічбаў 0, 1, 2, 3, 4, 5?}
Для гэтага павінна быць правіла, але, думаю, не трэба паўтараць злучнік.

2019-03-08 20:16 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Нумар карткі складаецца з паслядоўнасці трох літар з  $\{a, b, \dots, z \}$, якая следуе за паслядоўнасцю з трох лічбаў з $\{0, 1, \dots, 9 \}$. Колькі ёсць нумароў, калі адначасовае ўжыванне лічбы
Папраўлю

2019-03-08 20:18 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Знайдзіце колькасць 7-літарных пароляў, якія складаюцца з сімвалаў алфавіта $\{a, b, \dots, z \}$, якія: (а)~складаюцца з непаўторных літар; (б)~складаюцца з непаўторных літар і літары $a$ і $b$ не
Гэта са слоўніка, але твой варыянт гучыць таксама норм

2019-03-08 20:18 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Колькі існуе чатырохзначных натуральных лікаў, лічбы якіх не паўтараюцца і прыналежаць мноству $\{0, 1, 2, 3, 4, 5\}$? Колькі з іх цотных лікаў?}
Не бачу прынцыповай розніцы

2019-03-09 15:13 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе чатырохзначных натуральных лікаў, лічбы якіх не паўтараюцца і прыналежаць мноству $\{0, 1, 2, 3, 4, 5\}$? Колькі з іх цотных лікаў?}
"Колькі з іх" неяк вуха рэжа

2019-03-09 15:13 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе ўпарадкаваных пар $(a,b)$ натуральных лікаў $a$ і $b$, для якіх $\text{НАК}(a,b) = 2^{3} \cdot 5^{7}\cdot 11^{13}$?}
Так а ты знайшоў такія абазначэнні дзесьці ці проста па слове пераклаў і сабраў назад у абрэвіятуру?

2019-03-09 15:13 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе $n$-значных натуральных лікаў, якія дзеляцца на 4 і ўтвораныя з дапамогай лічбаў 0, 1, 2, 3, 4, 5?}
Спытаў у Машы яе меркаванне

2019-03-09 15:13 UTC, UladBohdan commented on problems_9/problems_9.tex
> +{Колькі існуе чатырохзначных натуральных лікаў, лічбы якіх не паўтараюцца і прыналежаць мноству $\{0, 1, 2, 3, 4, 5\}$? Колькі з іх цотных лікаў?}
Спытаў у Машы яе меркаванне

2019-03-09 19:04 UTC, KlicOgogo commented on problems_9/problems_9.tex
> +{Колькі існуе ўпарадкаваных пар $(a,b)$ натуральных лікаў $a$ і $b$, для якіх $\text{НАК}(a,b) = 2^{3} \cdot 5^{7}\cdot 11^{13}$?}
Па слове пераклаў)

2019-03-10 14:06 UTC, UladBohdan approved these changes

2019-03-10 14:41 UTC, merged