Problems 11-13
bsu-docs/discrete-mathematics-problems pull request #11
Opened 2019-03-27 19:31 UTC by UladBohdan

Q:
* `метад уключэння і выключэння` ці `метад уключэнняў і выключэнняў`?
* мо варта `ОБОРОНОСПОСОБНОСТЬ і МАТЕМАТИКА` замяніць на нешта іншае?

2019-03-27 19:42 UTC, KlicOgogo commented
- У слоўніку "ўлучэнне" і "вылучэнне".
- Са словамі не ведаю, можна нешта нейтральнае (англ)

2019-03-28 15:33 UTC, UladBohdan commented
ok so they are all translated but not fully ready for review yet.

* Questions in initial description are still relevant
* I've added a bunch of questions to our google doc
* I have some concerns about the indentations everywhere. We should probably improve out custom commands
* I would like to proofread all the pdf-s one more time

2019-04-11 07:49 UTC, KlicOgogo requested changes

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Ёсць 25 занумераваных месцаў. Колькі існуе спосабаў размясціць пяць чалавек на гэтых месцах,
"Занумараваных"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +
\bigskip або \smallskip? Задачы надта блізка стаяць, мне падаецца

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +
Таксама ёсць \medskip

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +(б) за круглым сталом (два размяшчэння за круглым сталом лічацца аднолькавымі,
"размяшчэнні", тут множны лік

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +каб ніякія дзве асобы аднаго пола не сядзелі побач?}
"полу", глядзі http://slounik.org/search?dict=&search=пол&x=0&y=0

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +каб кожны лік, кратны 2, і кожны лік, кратны 3, мелі парадкавыя нумары кратныя,
Блытанка з лікамі ("лік" спачатку ў адзіночным ліку, а пасля ідзе "мелі"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Размещения. Перестановки.}
Водступ для рускамоўнай версіі не вельмі прыгожы

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Размещения. Перестановки.}
Далей аналагічна

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{На плоскасці праведзеныя $n$ прамых $(n \ge 2)$, прычым ніякія дзве з іх не паралельны
"паралельныя"?

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +\guillemotleft рэшак\guillemotright і шасці \guillemotleft арлоў\guillemotright?
У пдф-цы перад "і" не стаіць прабел. Лепш ужывай << і >> замест гэтых страшэнных каманд, у рускамоўнай версіі таксама.

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Сярод 20 чалавек, 10 -- фізікі, а іншыя 10 -- матэматыкі. Знайдзіце колькасць спосабаў,
Я ужываў доўгі працяжнік, ("---), ён кананічны ў кірылічнай тусе

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Вызначыце колькасць пяцізначных натуральных лікаў, дзесятковы запіс якіх змяшчае розна дзве адрозныя лічбы?}
"роўна"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +і тры няцотныя лічбы? Вызначыце колькасць $2n$-значных $(n \ge 1)$ натуральных лікаў,
Калі лік натуральны, ён і так $\ge 1$, думаю, лішні раз не трэба паўтараць. Калі ёсць яшчэ, таксама варта прыбраць

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +занумераваныя лікамі $1, 2, \ldots, n$. Колькі існуе спосабаў абраць пяць карт так,
"занумараваныя"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +аднолькавай масці; (в) як мінімум чатыры карты адной масці; (г) карта ўсіх масцей;
"карты ўсіх масцей"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +з адрознымі намерамі?}
"нумарамі"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Колькі існуе бінарных вектароў даўжыні $m + n$, якія змяшчаюць $m$ адзінак і
"вектараў", мне не падабаецца памылковы варыянт, які сілком зацягнулі

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +($m \le n$) на $m + n$ занумераваных месцах так, каб ніякія два мужчыны не сядзелі побач?}
"занумараваных"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Колькі існуе спосабаў саставіць трыкутнікі, даўжыні бакоў якіх з'яўляюцца натуральнымі лікамі,
Мб лепей "пабудаваць", чым "саставіць"?

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +(а) хаця б на адной касці выпадзе 6 ачкоў; (б) роўна на адной касці выпадзе 6 ачкоў;
"косці", http://slounik.org/search?dict=&search=косць&x=0&y=0

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +(в) на адной з касцёў выпадзе 1 ачко, а на іншай -- 2 ачка?}
"касцей"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +(в) на адной з касцёў выпадзе 1 ачко, а на іншай -- 2 ачка?}
"ачкі"

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +неадмоўных ліках (натуральных ліках): (а) раўнання $x_1 + x_2 + \ldots + x_n = r$;
натуральныя і цэлыя неадмоўныя не адно і тое ж

2019-04-11 07:49 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +{Колькі існуе спосабаў тром людзям раздзяліць паміж сабой 6 аднолькавых яблыкаў,
"падзяліць"?

2019-04-11 07:50 UTC, KlicOgogo commented
These remarks are only for problems_10.

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +праз перастаноўку літар у слове \guillemotleft ОБОРОНОСПОСОБНОСТЬ\guillemotright\ так, каб:
Floccinaucinihilipilification - давай возьмем гэта чоткае слова.
https://www.grammarly.com/blog/14-of-the-longest-words-in-english/

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +праз перастаноўку літар у слове \guillemotleft ОБОРОНОСПОСОБНОСТЬ\guillemotright\ так, каб:
<< і >> для двукоссяў, тут і далей па доку

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +праз перастаноўку літар у слове \guillemotleft МАТЕМАТИКА\guillemotright\ так, каб:
Са словам "МАТЭМАТЫКА" задача ідэнтычная

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +  \item ніякія тры літары \guillemotleft О\guillemotright\ не ішлі адна за адной.
"ішлі запар"?

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +{У скрынцы ляжаць тры блакітныя, тры чырвоныя і чатыры зялёныя шары (шары аднаго колера
"колеру", http://slounik.org/search?dict=&search=колер&x=0&y=0

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +з лічбаў ліка 75\,\,226\,\,522.}
"ліку", http://slounik.org/search?dict=&search=%D0%BB%D1%96%D0%BA&x=0&y=0

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +з лічбаў ліка 11\,\,223\,\,334 пры ўмове, што тры лічбы 3 не ідуць адна за адной.}
"ліку"

2019-04-12 22:23 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +факта на большыя размернасці.}
"памернасці"

2019-04-12 22:23 UTC, KlicOgogo commented
There are remarks for problems_11

2019-04-12 22:28 UTC, KlicOgogo commented on problems_12/problems_12.tex
> +  \item $S(n, k) = k \cdot S(n - 1, k) + S(n - 1, k - 1)$, дзе $n \ge k \ge 1$ -- цэлыя лікі,
"--- працяжнік, тут і далей

2019-04-12 22:28 UTC, KlicOgogo commented on problems_12/problems_12.tex
> +Няхай $X$ --- канечнае $n$-элементнае мноства. Дакажыце, што колькасць усіх
Аналагічна з працяжнікам

2019-04-12 22:28 UTC, KlicOgogo commented on problems_12/problems_12.tex
> +\problemItemWithCommonPart
Адлегласці паміж задачамі таксе, можна забіць на тое, каб памясціцца на адну старонку

2019-04-12 22:29 UTC, KlicOgogo commented
There are remarks for problems_12

2019-04-12 22:57 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +\biLangHeader
Каманда адназначна патрабуе апгрэйд

2019-04-12 22:57 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +ведаюць ангельскую мову, 31 -- нямецкую мову, 52 -- французскую мову.
Працяжнік

2019-04-12 22:57 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +а) тры зафіксаваныя элементы $a$, $b$, $c$ з $X$ не ідуць адно за адным (у любым парадку);
"адзін за адным"? "Элемент" мужчынскага роду.

2019-04-12 22:57 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +
Адлегласці?

2019-04-12 22:57 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +{Колькі лікаў можна ўтварыць перастаноўкай лічбаў ліка $1~234~114~546$ так, каб:
"ліку"

2019-04-12 22:57 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +{Паслядоўнасць даўжыні 6, складзеныя з лічбаў, называецца \emph{шчаслівай},
"складзеная"

2019-04-12 22:57 UTC, KlicOgogo commented
There are remarks for problems_13

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +{14. Рэкурэнтныя стасункі.}
А як жа "судачыненні"?)

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +пры гэтым размясціўшы іх у адну лінію (парадак размяшчэння марак -- істотны).}
"---

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +агульную суму 40 капеек, калі можна выкарыстоўваць маркі вартасцю 5, 10, 15 альбо 20 капеек,
"вартасцю"? Мне здаецца, гэта слова тут не вельмі трапна ужыта. Мабыць, "кошту"?

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +$x_1 \le x_2 \ge x_3 \le x_4 \ge x_5 \le \ldots\,\,$.}
Формула кепска выглядае на пдф-цы

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +
Адлегласці

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +{Вызначыце колькасць пароляў даўжыні 7, якія складаюцца з літар ангельскага алфавіта
У нас да гэтага былі тарашкевіцкія словы? Калі не, то мб лепш ужыць "англійскага"?

2019-04-12 23:08 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +{Знайдзіце агульнае рашэнне лінейных аднародных рэкурэнтных стасункаў з пастаяннымі каэфіцыентамі:}
"судачыненняў"

2019-04-12 23:08 UTC, KlicOgogo commented
There are remarks for problems_14

2019-04-12 23:18 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +  \item $F(n) = \sum_{i = 0}^n f(i)$, $n = 0, 1, 2, \ldots\, $;
\sum \limits

2019-04-12 23:18 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +{Чатыры чалавека па чарзе кідаюць ігральную косць. Знайдзіце колькасць спосабаў,
"чалавекі"

2019-04-12 23:18 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +{У скрынцы знаходзяцца 2 белых, 3 чырвоных, 8 зялёных і 9 аранжавых шароў.
Я б удакладніў напісанне прыметнікаў

2019-04-12 23:18 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +ёсць чырвоны, колькасць абраных зялёных шароў --- цотная, а колькасць аранжавых шароў --- няцотная.}
"---

2019-04-12 23:18 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +
Адлегласці

2019-04-12 23:18 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +{Используя производящие функции, решите следующие рекуррентные соотношения:}
"судачыненні"

2019-04-17 17:24 UTC, UladBohdan commented on problems_10/problems_10.tex
> +каб кожны лік, кратны 2, і кожны лік, кратны 3, мелі парадкавыя нумары кратныя,
"кожны лік, кратны 2, і кожны лік, кратны 3, [ТО БОК ДВА ЛІКІ] мелі парадкавыя нумары"

ок жэ
у чым праблема

2019-04-17 17:24 UTC, UladBohdan commented on problems_10/problems_10.tex
> +{Размещения. Перестановки.}
Гэта ты зараз фіксіш у іншым ПР.

2019-04-17 17:35 UTC, KlicOgogo commented on problems_10/problems_10.tex
> +каб кожны лік, кратны 2, і кожны лік, кратны 3, мелі парадкавыя нумары кратныя,
Блін, і праўда, чот я)
"то-бок" тока)

2019-04-17 17:38 UTC, UladBohdan commented on problems_10/problems_10.tex
> +{Колькі існуе бінарных вектароў даўжыні $m + n$, якія змяшчаюць $m$ адзінак і
гвалтоўна зацягнулі, я б нават сказаў

2019-04-17 17:39 UTC, UladBohdan commented on problems_10/problems_10.tex
> +{Колькі існуе спосабаў саставіць трыкутнікі, даўжыні бакоў якіх з'яўляюцца натуральнымі лікамі,
ок

2019-04-17 17:41 UTC, UladBohdan commented on problems_10/problems_10.tex
> +неадмоўных ліках (натуральных ліках): (а) раўнання $x_1 + x_2 + \ldots + x_n = r$;
прыбраў згадванне "натуральных" лікаў

2019-04-17 17:51 UTC, UladBohdan commented on problems_11/problems_11.tex
> +факта на большыя размернасці.}
размернасць - памернасць?..

2019-04-17 17:55 UTC, UladBohdan commented on problems_13/problems_13.tex
> +\biLangHeader
у тваім ПР !

2019-04-17 17:55 UTC, UladBohdan commented on problems_13/problems_13.tex
> +ведаюць ангельскую мову, 31 -- нямецкую мову, 52 -- французскую мову.
спакуха, паўсюль глабальна памяняў

2019-04-17 17:56 UTC, UladBohdan commented on problems_13/problems_13.tex
> +
чо?

2019-04-17 17:59 UTC, UladBohdan commented on problems_14/problems_14.tex
> +{14. Рэкурэнтныя стасункі.}
А гэта я за "судачыненні" тапіў?..
не
ты хочаш тут судачыненні?

2019-04-17 17:59 UTC, UladBohdan commented on problems_14/problems_14.tex
> +агульную суму 40 капеек, калі можна выкарыстоўваць маркі вартасцю 5, 10, 15 альбо 20 капеек,
Памяняў. Але ў транспарце ж кажуць "разлічвайцеся купюрамі намінальнай вартасцю не больш за ..."

2019-04-17 18:00 UTC, UladBohdan commented on problems_14/problems_14.tex
> +агульную суму 40 капеек, калі можна выкарыстоўваць маркі вартасцю 5, 10, 15 альбо 20 капеек,
Хаця мінсктранс так сабе аўтарытэт канешне

2019-04-17 18:00 UTC, UladBohdan commented on problems_14/problems_14.tex
> +$x_1 \le x_2 \ge x_3 \le x_4 \ge x_5 \le \ldots\,\,$.}
Таму што ў радок не ўпісалася?

2019-04-17 18:01 UTC, UladBohdan commented on problems_14/problems_14.tex
> +
у пдфцы ці ў кодзе?

2019-04-17 18:01 UTC, UladBohdan commented on problems_14/problems_14.tex
> +{Вызначыце колькасць пароляў даўжыні 7, якія складаюцца з літар ангельскага алфавіта
гэта не тое каб тарашкевіцкае..
але ладна, ок

2019-04-17 18:01 UTC, UladBohdan commented on problems_14/problems_14.tex
> +{Вызначыце колькасць пароляў даўжыні 7, якія складаюцца з літар ангельскага алфавіта
зануда ты

2019-04-17 18:02 UTC, UladBohdan commented on problems_14/problems_14.tex
> +{14. Рэкурэнтныя стасункі.}
Ладна, ок. але мне напружвае

2019-04-17 18:04 UTC, UladBohdan commented on problems_15/problems_15.tex
> +  \item $F(n) = \sum_{i = 0}^n f(i)$, $n = 0, 1, 2, \ldots\, $;
?

2019-04-17 18:04 UTC, UladBohdan commented on problems_15/problems_15.tex
> +{У скрынцы знаходзяцца 2 белых, 3 чырвоных, 8 зялёных і 9 аранжавых шароў.
ціпа
"2 белыя, 3 чырвоныя, ... " трэба ?

2019-04-17 18:06 UTC, UladBohdan commented on problems_15/problems_15.tex
> +
я не разумею :(

2019-04-17 18:12 UTC, KlicOgogo commented on problems_13/problems_13.tex
> +
Гэта па ходу было заўвага пра \...skip

2019-04-17 18:13 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +$x_1 \le x_2 \ge x_3 \le x_4 \ge x_5 \le \ldots\,\,$.}
Так

2019-04-17 18:13 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +
У пдф

2019-04-17 18:13 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +  \item $F(n) = \sum_{i = 0}^n f(i)$, $n = 0, 1, 2, \ldots\, $;
Калі так напішаш, _{i=0} ^n лягуць прыгожа

2019-04-17 18:14 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +{У скрынцы знаходзяцца 2 белых, 3 чырвоных, 8 зялёных і 9 аранжавых шароў.
Я вось і не ведаю) 
Думаецца, прыметнік павінны падпарадкоўвацца лічэбніку

2019-04-17 18:14 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +
\...skip

2019-04-17 18:19 UTC, KlicOgogo commented on problems_11/problems_11.tex
> +факта на большыя размернасці.}
У слоўніку так напісана

2019-04-17 18:24 UTC, UladBohdan commented on problems_11/problems_11.tex
> +факта на большыя размернасці.}
ок дадаў у гугл док

2019-04-17 18:26 UTC, UladBohdan commented on problems_14/problems_14.tex
> +
усё яшчэ не разумею

2019-04-17 18:29 UTC, UladBohdan commented on problems_15/problems_15.tex
> +  \item $F(n) = \sum_{i = 0}^n f(i)$, $n = 0, 1, 2, \ldots\, $;
`$F(n) = \sum \limit_{i = 0}^n` - так ?

2019-04-17 18:29 UTC, KlicOgogo commented on problems_15/problems_15.tex
> +  \item $F(n) = \sum_{i = 0}^n f(i)$, $n = 0, 1, 2, \ldots\, $;
$F(n) = \sum \limits _{i = 0}^n

2019-04-17 18:30 UTC, KlicOgogo commented on problems_14/problems_14.tex
> +
Проста нагадаў пад кожным файлам

2019-04-17 18:30 UTC, UladBohdan commented on problems_15/problems_15.tex
> +{У скрынцы знаходзяцца 2 белых, 3 чырвоных, 8 зялёных і 9 аранжавых шароў.
Спытаў у Бадзейкі

2019-04-17 18:31 UTC, UladBohdan commented on problems_15/problems_15.tex
> +  \item $F(n) = \sum_{i = 0}^n f(i)$, $n = 0, 1, 2, \ldots\, $;
а, топчык

2019-04-17 18:38 UTC, KlicOgogo approved these changes

2019-04-17 18:42 UTC, merged