Update command for term 2
bsu-docs/discrete-mathematics-problems pull request #28
Opened 2019-08-04 15:56 UTC by KlicOgogo

2019-08-09 05:36 UTC, UladBohdan reviewed
Don't forget to update the doc with new translations!

docs.google.com/document/d/1gW8Z4fcFTKQFpv_hC44niSqE9vobKvVrvqJvXAvdceY

2019-08-09 05:36 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +{Высветліць, ці з'яўляецца функцыя $f$ самадваістай:}
Чамусьці змяніўся стыль у параўнанні з першым семестрам: раней было заўжды "высветліцЕ", "вызначыцЕ", а не "высветліць", "вызначыць". Мо варта прытрымлівацца старога стылю?

2019-08-09 05:36 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +а якія на $\overline{x}$ з тым, каб атрымаць канстанту:}
Не зусім разумею гэтае "з тым" (і ў расейскай версіі таксама).

2019-08-09 05:36 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +{Уявіўшы функцыю $f$ паліномам Жэгалкіна, высветліць, ці з'яўляецца яна лінейнай:}
Па-першае, у слова "уяўляць" іншае значэнне ўсё ж, я думаю.
Па-другое, дзіўная форма. Давай перафармулюем:
"Функцыя f прадстаўленая паліномам Жэгалкіна: высветліць, ці ..."

2019-08-09 05:36 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +указаўшы манатонныя функцыі, якія не змяшчаюцца ў адпаведных класах.}
можа атрымаецца пазбегнуць формы "указаўшы"?..

2019-08-09 05:36 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +{Падлічыць колькасць шэферных функцый у $P_2^n$.}
шэферных ці шэферавых?
гэта па імені?

2019-08-09 19:06 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +{Падлічыць колькасць шэферных функцый у $P_2^n$.}
Гэта ад імя ўтворана? Значыцца, шэферавых?

2019-08-09 19:06 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +указаўшы манатонныя функцыі, якія не змяшчаюцца ў адпаведных класах.}
Зраблю

2019-08-09 19:06 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +а якія на $\overline{x}$ з тым, каб атрымаць канстанту:}
Перафармулюю

2019-08-09 19:06 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +{Уявіўшы функцыю $f$ паліномам Жэгалкіна, высветліць, ці з'яўляецца яна лінейнай:}
Добра

2019-08-09 19:07 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +{Высветліць, ці з'яўляецца функцыя $f$ самадваістай:}
Дык і код змяніўся, думаю, можна ў старым стылі пісаць

2019-08-15 10:53 UTC, UladBohdan requested changes

2019-08-15 10:53 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +{Функцыя $f$ прадстаўленая паліномам Жэгалкіна, высветліце, ці з'яўляецца яна лінейнай:}
можа тут кропку з коскай пасля "Жэгалкіна"?

2019-08-15 10:53 UTC, UladBohdan commented on term_02/problems_03/problems_03.tex
> +{Праверце ці з'яўляецца функцыя $f$ манатоннай:}
коска!

2019-08-15 10:57 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +{Праверце ці з'яўляецца функцыя $f$ манатоннай:}
Сапраўды

2019-08-15 10:57 UTC, KlicOgogo commented on term_02/problems_03/problems_03.tex
> +{Функцыя $f$ прадстаўленая паліномам Жэгалкіна, высветліце, ці з'яўляецца яна лінейнай:}
Навошта? Проста складаны сказ

2019-08-15 16:37 UTC, UladBohdan approved these changes

2019-08-15 18:48 UTC, merged