Problems _04, _07-08, _11-12
bsu-docs/discrete-mathematics-problems pull request #29
Opened 2019-08-18 11:53 UTC by KlicOgogo

2019-08-20 16:00 UTC, UladBohdan requested changes
01  ✅
02  ✅

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +{1. Асноўныя звесткі аб булевых зменных. Спрашчэнні формул. Істотныя і фіктыўныя зменныя.}
можа лепш "пра" булевыя зменныя? гучыць лепей

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +Знайдзіце колькасць функцый у $P^2_n$ (т.-б. функцый, якія залежаць ад зменных $x_1, x_2, \ldots, x_n$), для якіх выконваецца ўмова:
ненатуральнае скарачэнне :) можа проста "то-бок"?

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +    \item на дадзеных $I$ наборах значэнні фіксаванныя, а на астатніх адвольныя ($0 \le l \le 2^n - 1$, $n \ge 1$);
`$l$` наборах (маленькае Л)

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +    \item на дадзеных $I$ наборах значэнні фіксаванныя, а на астатніх адвольныя ($0 \le l \le 2^n - 1$, $n \ge 1$);
фіксаваНыя

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +    \item на дадзеных $I$ наборах значэнні фіксаванныя, а на астатніх адвольныя ($0 \le l \le 2^n - 1$, $n \ge 1$);
мо працяжнік перад "астатніх"?

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +, якая атрымліваецца з яе пры перастаноўцы зменных $x_1$ і $x_2$ ($n \ge 2$);
лішняя коска і павінны новы пункт тут быць

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +    \item функцыя $f(\tilde x^n)$ \textit{сіметрычная}, т.-б. $f(x_1, x_2, \ldots, x_n) = f(x_{i_1}, x_{i_2}, \ldots, x_{i_n})$ пры любой перастаноўцы $(i_1, i_2, \ldots, i_n)$, $n \ge 1$.
давай не пісаць "т.-б."

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +(рэалізаваўшы для гэтага функцыю  $f$ формулай, якая яўна не змяшчае зменную $x_1$):}
давай не злоўжываць гэтай формы, яна нейкая не вельмі беларуская

"для гэтага рэалізуйце функцыю формулай..."

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +(рэалізаваўшы для гэтага функцыю  $f$ формулай, якая яўна не змяшчае зменную $x_1$):}
"яўна не змяшчае"
лепей: "не змяшчае яўна"

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +{Знайдзіце колькасць функцый у $P_n^2$, якія адпавядаюць умове: існуе пара супрацьлеглых набораў,
а што такое "супрацьлеглыя наборы"?

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +Праз $P^c_n\ (n \ge 1)$ абазначым мноства ўсіх булевых функцый, якія залежаць ад зменных $x_1, x_2, \ldots, x_n$ і пры гэтым ад кожнай функцыі істотным чынам.
> і пры гэтым ад кожнай функцыі істотным чынам

няправільна сэнс перадаў
"от каждой из них" - маюцца на ўвазе зменныя, а не функцыі

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_01/problems_01.tex
> +    \item Выпішыце ўсе функцыі мноства $P^c_2$;
у задачы 1 у гэтай пдф-цы кожны пункт ты пачынаў з маленькай літары. а тут з вялікай. негоже.

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{2. Асноўныя ўяўленні булевых функцый: ДНФ, КНФ, КДНФ, ККНФ, паліном Жэгалкіна.}
не ну тут жа не ўяўленні. а "прадстаўленні"

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{2. Асноўныя ўяўленні булевых функцый: ДНФ, КНФ, КДНФ, ККНФ, паліном Жэгалкіна.}
слухай, а можа не перакладаць гэтыя абрэвіятуры? на практыцы іншыя абрэвіятуры наўрад ці нехта будзе юзаць, надта складана стасавацца становіцца

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{2. Асноўныя ўяўленні булевых функцый: ДНФ, КНФ, КДНФ, ККНФ, паліном Жэгалкіна.}
плюс я калі для сябе перакладаў
то "совершенная" перакладаў як "дасканалая"
то-бок СКНФ - ДКНФ
а што ў цябе такое "К" ? :)

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{З дапамогай эквівалентных пераўтварэнняў пабудуйце д.н.ф. функцыі $f(\tilde x^n)$:}
а можа паўсюль юзаць абрэвіятуры ціпа "ДНФ", а не маленькімі літарамі з кропачкамі. выглядае больш натуральна

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Карыстаючыся эквівалентнымі пераўтварэннямі, пабудуйце к.н.ф. функцыі $f(\tilde x^n)$:}
Можа "Праз эквівалентныя пераўтварэнні..." ?

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Карыстаючыся эквівалентнымі пераўтварэннямі, пабудуйце к.н.ф. функцыі $f(\tilde x^n)$:}
Ці "З дапамогай"

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Уявіце ў канчатковай д.н.ф. наступныя функцыі:}
Прадстаўце

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Уявіце ў канчатковай д.н.ф. наступныя функцыі:}
Ааа "К" - гэта "канчатковы"
хмхм Канчатковы напэўна больш сэнсу мае чым Дасканалы

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Уявіце ў выглядзе канчатковай к.н.ф. наступныя функцыі:}
Прадстаўце

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Пераўтварыўшы вектар значэнняў функцыі $f(\tilde x^n)$, пабудуйце паліном Жэгалкіна для гэтай функцыі, калі:}
Не злоўжывай гэтымі формамі :((

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Уявіце функцыю $f(\tilde x^n)$ формулай над мноствам звязак $\{\&, -\}$,
Прадстаўце

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +пераўтварыце далей атрыманую формулу ў паліном Жэгалкіна функцыі $f(\tilde x^n)$,
слова "далей" падаецца лішнім

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +пераўтварыце далей атрыманую формулу ў паліном Жэгалкіна функцыі $f(\tilde x^n)$,
і коска ў канцы радка дзіўная (і ў рускай версіі таксама)

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Няхай мноствы $X^m=\{x_1, \ldots, x_m\}$ і $Y^n=\{y_1, \ldots, y_n\}$ не перасякаюцца. Дапускаючы, што даўжыні канчатковых д.н.ф. функцый $f(\tilde x^m)$ і $g(\tilde y^n)$ роўныя адпаведна $k$ і $l$
"не перакрыжоўваюцца" ?

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Няхай мноствы $X^m=\{x_1, \ldots, x_m\}$ і $Y^n=\{y_1, \ldots, y_n\}$ не перасякаюцца. Дапускаючы, што даўжыні канчатковых д.н.ф. функцый $f(\tilde x^m)$ і $g(\tilde y^n)$ роўныя адпаведна $k$ і $l$
"Дапускаючы" - Няхай?

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Няхай мноствы $X^m=\{x_1, \ldots, x_m\}$ і $Y^n=\{y_1, \ldots, y_n\}$ не перасякаюцца. Дапускаючы, што даўжыні канчатковых д.н.ф. функцый $f(\tilde x^m)$ і $g(\tilde y^n)$ роўныя адпаведна $k$ і $l$
то-бок замяніць на "Няхай"

2019-08-20 16:00 UTC, UladBohdan commented on term_02/problems_02/problems_02.tex
> +{Высветліце, на якой колькасці набораў з $B^n$ абарачваецца ў 1 паліном $P(\tilde x^n)=\bigoplus\limits_{i=2}^n x_1x_i$, $n \ge 2$.}
"прымае значэнне"? "пераўтвараецца"?

2019-08-20 16:06 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +{2. Асноўныя ўяўленні булевых функцый: ДНФ, КНФ, КДНФ, ККНФ, паліном Жэгалкіна.}
Канчатковая

2019-08-20 16:07 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +{Высветліце, на якой колькасці набораў з $B^n$ абарачваецца ў 1 паліном $P(\tilde x^n)=\bigoplus\limits_{i=2}^n x_1x_i$, $n \ge 2$.}
"прымае значэнне"

2019-08-20 16:11 UTC, KlicOgogo commented on term_02/problems_01/problems_01.tex
> +{1. Асноўныя звесткі аб булевых зменных. Спрашчэнні формул. Істотныя і фіктыўныя зменныя.}
Сапраўды

2019-08-20 16:13 UTC, KlicOgogo commented on term_02/problems_01/problems_01.tex
> +, якая атрымліваецца з яе пры перастаноўцы зменных $x_1$ і $x_2$ ($n \ge 2$);
Тут я неяк прафукаў радок, дакіну

2019-08-20 16:15 UTC, KlicOgogo commented on term_02/problems_01/problems_01.tex
> +    \item на дадзеных $I$ наборах значэнні фіксаванныя, а на астатніх адвольныя ($0 \le l \le 2^n - 1$, $n \ge 1$);
Хай будзе

2019-08-20 16:18 UTC, KlicOgogo commented on term_02/problems_01/problems_01.tex
> +{Знайдзіце колькасць функцый у $P_n^2$, якія адпавядаюць умове: існуе пара супрацьлеглых набораў,
Іх xor адзінкавы, я так разумею

2019-08-20 16:20 UTC, KlicOgogo commented on term_02/problems_01/problems_01.tex
> +    \item Выпішыце ўсе функцыі мноства $P^c_2$;
Тут новы сказ, а там нешта пасля двухкроп'я, усё лагічна

2019-08-20 16:20 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +{2. Асноўныя ўяўленні булевых функцый: ДНФ, КНФ, КДНФ, ККНФ, паліном Жэгалкіна.}
> не ну тут жа не ўяўленні. а "прадстаўленні"

Я ў слоўніку глядзеў

2019-08-20 16:24 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +{2. Асноўныя ўяўленні булевых функцый: ДНФ, КНФ, КДНФ, ККНФ, паліном Жэгалкіна.}
Ёсць яшчэ варыянт "выяўленне"

2019-08-20 16:24 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +{З дапамогай эквівалентных пераўтварэнняў пабудуйце д.н.ф. функцыі $f(\tilde x^n)$:}
Добра

2019-08-20 16:55 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +{Няхай мноствы $X^m=\{x_1, \ldots, x_m\}$ і $Y^n=\{y_1, \ldots, y_n\}$ не перасякаюцца. Дапускаючы, што даўжыні канчатковых д.н.ф. функцый $f(\tilde x^m)$ і $g(\tilde y^n)$ роўныя адпаведна $k$ і $l$
Перафармулюю і выпраўлю

2019-08-20 16:55 UTC, KlicOgogo commented on term_02/problems_02/problems_02.tex
> +пераўтварыце далей атрыманую формулу ў паліном Жэгалкіна функцыі $f(\tilde x^n)$,
Сапраўды

2019-08-28 01:01 UTC, UladBohdan approved these changes

2019-08-28 05:19 UTC, merged